### PR TITLE
Add TranslateWithLang method

### PR DESCRIPTION
**Pull request by stanislas-m**
This allows to translate without using a buffalo.Context

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Found some fixes!

_P.S. share your ideas, feedbacks or issues with us at https://github.com/fixmie/feedback (this message will be removed after the beta stage)._

**Comment by kteb** [comment]
I didn't see any test on TranslateWithLang (even though the tests were rewritten to reduce the dependencies). 

Did I miss something ?

**Comment by stanislas-m** [comment]
True. I'll add some tests.

**Comment by Baggerone** [comment]
I suppose you got notified automatically, but just in case you didn't ...
https://github.com/gobuffalo/mw-i18n/compare/master...Baggerone:patch-1?expand=1

Sorry, that should have been ...
https://github.com/gobuffalo/mw-i18n/pull/5

**Comment by stanislas-m** [comment]
Thanks @Baggerone!

**Comment by Baggerone** [comment]
You're welcome.  Thanks for the actual function!

**Pull request merged**
